### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by userlol24** [Tetrax-10/letterboxd-custom-images#1]
When I click on the three dots on my profile or next to a movie I don't get any extra options that weren't there before even though it is running and the gear icon doesn't appear in the tampermonkey menu either. What should I do?

**Comment by Tetrax-10** [comment]
Make sure you installed by checking the dashboard. If yes what browser are you using, Then what URL are you on?

**Comment by userlol24** [comment]
I just tried reinstalling it but no luck. I'm using google chrome. First pic is what I see when I click on any movie, second pic is letterboxd homepage
<img width="215" alt="letterboxd3" src="https://github.com/user-attachments/assets/10920fec-7af7-4f52-a3a2-8cfcdd90f8fd">
<img width="259" alt="letterboxd2" src="https://github.com/user-attachments/assets/9e145d04-0019-4d89-b796-5fa56dbb7d95">
<img width="213" alt="letterboxd" src="https://github.com/user-attachments/assets/d5579a90-3771-4ea3-afaf-1db784ded9ab">

**Comment by userlol24** [comment]
Enabling developer mode didn't do anything yesterday but it worked today! Thank you :)
